version: '3'

services:
  app:
    build:
      context: node
    container_name: app
    networks:
      - node-network
    volumes:
      - ./node:/usr/source/app
    tty: true
    ports:
      - '3000:3000'

  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - '8080:80'
    networks:
      - node-network

  db:
    platform: linux/x86_64
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
